### ISSUE TITLE
[Feature Request] Allow HTML <header> tag

### ISSUE THREAD

**Issue by sectsect** [FilipChalupa/hiding-header-react#1]
Thanks for useful package.

It would be very useful to have a property that allows us to replace the container HTML element `<div>` with a `<header>` tag.

```diff
return (
-  <div className={className} ref={container}>
+  <header className={className} ref={container}>
    <div className={innerClassName}>
      <Context.Provider value={hidingHeaderInstance}>
        {children}
      </Context.Provider>
    </div>
-  </div>
+  </header>
)
```

**Comment by FilipChalupa** [comment]
Thank you for the suggestion. It didn't occur to me as I usually do `<HidingHeader><header>my content</header></HidingHeader>`.

However thanks to you now I know that specifying custom element type may be beneficial.

Can you please test `npm install hiding-header-react@0.6.1` with `<HidingHeader component="header">…</HidingHeader>` and tell me whether it solves your case?

<img width="365" alt="image" src="https://user-images.githubusercontent.com/1045362/155820100-e778466c-60ea-445e-8883-bb9817757e29.png">


<img width="413" alt="image" src="https://user-images.githubusercontent.com/1045362/155820029-48e27c21-ddbc-4149-bfbc-1ee4a61c8f9c.png">

**Comment by sectsect** [comment]
@FilipChalupa 

Thanks for your support.

This update works fine, and the behavior I expected.

Thank you.
