### ISSUE TITLE
My package for Solid.js 

### ISSUE THREAD

**Issue by sectsect** [FilipChalupa/hiding-header-react#2]
@FilipChalupa 

Thanks for your useful package.
I have multiple projects using this package and love it.

I am currently developing a package for [Solid.js](https://www.solidjs.com/) based on your package [Hiding Header React](https://github.com/FilipChalupa/hiding-header-react).
Its development is almost complete and I hope to publish it in the next few days.

I wanted to let you know in advance, so I contacted you through this Github Issue.

And, I would like to ask you for the following permission.
What do you think?
- May I include **your credit and a link to the demo site** in the README?
- May I reuse part of [README](https://github.com/FilipChalupa/hiding-header-react/blob/main/README.md) for my package? (GIF image or description)

Sorry for my poor english.
Thank you.

**Comment by FilipChalupa** [comment]
I'm happy to hear that. I would love to see a port to Solid.js. Thank you for making it. 🙂

> May I include your credit and a link to the demo site in the README?

Are you using [Hiding Header (not React)](https://www.npmjs.com/package/hiding-header) as a dependency in your `package.json`? If so, I don't expect any other kind of credit. I would be ok with more than that but don't require it.

> May I reuse part of [README](https://github.com/FilipChalupa/hiding-header-react/blob/main/README.md) for my package? (GIF image or description)

Feel free to reuse any part of the README, GIF, description, link to demo.

Is there anything I can do on my part? Do you need some API clarification or anything else?

**Comment by sectsect** [comment]
@FilipChalupa 

> Are you using [Hiding Header (not React)](https://www.npmjs.com/package/hiding-header) as a dependency in your package.json?

Yes. I'm using 'Hiding Header' as a dependency.
```json
"dependencies": {
  "hiding-header": "^0.8.3"
},
```
I'm going to mention in the README that the package was forked from **Hiding Header React** repository.

> Feel free to reuse any part of the README, GIF, description, link to demo.

Thank you so much.

I have nothing to ask of you at this time.
I will let you know after I publish the package. 🙂

**Comment by sectsect** [comment]
@FilipChalupa 

Hello, I have published a package.
Now available.

Please let me know if there are any problems.
Thank you.


https://github.com/sectsect/solid-hiding-header

**Comment by FilipChalupa** [comment]
Nice. I will try it later today.

**Comment by FilipChalupa** [comment]
Works like a charm. Thank you.

(My demo experiment https://codesandbox.io/s/solid-hiding-header-0gw0r4?file=/index.html)

**Comment by FilipChalupa** [comment]
FYI I've mentioned your package in the [Hiding Header readme](https://www.npmjs.com/package/hiding-header).

**Comment by sectsect** [comment]
@FilipChalupa 
Thanks for your support.
